#!/usr/bin/bash

for snr in 0 10 20 30; do
  python3 gen_test.py \
    --test-list /data/hejung/timit/test_w2v.wav.phone \
    --noise-list musan_test.list --snr $snr --output timit_test_w2v/snr$snr
done
