#!/usr/bin/bash

for exp in $(ps -u hejung -f -www | grep -E "train.py|train_w2v.py|train_viz.py" | grep -v grep \
  | grep -o "\-\-output\s*[/0-9a-zA-Z_.]*" | awk '{print $2}'); do 
  echo $exp; head -n1 $exp/ARGS; tail -n3 $exp/train.log; echo ''; 
done
